"""
recovery_tips_engine.py — deterministic replacement for the `recovery`
section of the plan schema (daily_nonneg, key_numbers, tip_sections),
which used to be free-generated by Gemini on every /result call.

This is editorial content (sleep/hydration/movement guidance), not KB
data — there's no external dataset to source it from, so it's a curated
bank written once, same category of content as the static
`_RECOVERY_DEFAULT` fallback already in fitness_generator.py (that
fallback's exact wording is kept as tip_sections[0]/[1] here, so nothing
a user has already seen changes meaning — this only adds more variety
around it, not replaces it with something unrecognizable).

Rotation is deterministic, not random: which tips show is a function of
(member_id, cycle_number), so regenerating the same cycle always returns
the same tips (reproducible, testable), but cycle N+1 shows a different
subset than cycle N (so a multi-cycle member doesn't see byte-identical
recovery copy every time, which is the one real thing Gemini's free
generation gave that a single static block didn't).

daily_nonneg / key_numbers targets are goal/experience-aware (a recovery-
flagged goal gets a higher sleep target and lower step floor than a
fat-loss goal, for example) rather than one fixed set for every profile —
still deterministic, just not identical across every goal type the way
the single static fallback was.
"""

from __future__ import annotations

import hashlib


def _stable_pick(seed_parts: tuple, pool_size: int, count: int) -> list[int]:
    """Deterministic, reproducible index selection — same seed always
    returns the same indices, different (member_id, cycle_number) pairs
    spread across the pool. Not true randomness, doesn't need to be."""
    seed_str = "|".join(str(p) for p in seed_parts)
    digest = hashlib.sha256(seed_str.encode()).hexdigest()
    start = int(digest[:8], 16) % pool_size
    return [(start + i) % pool_size for i in range(count)]


_SLEEP_TIPS = (
    "No screens 60 min before bed",
    "No caffeine after 2 PM",
    "Morning sunlight within 30 min of waking",
    "Cool room, dark environment = deeper sleep",
    "Consistent sleep/wake time, even on rest days",
    "Avoid a heavy meal in the 2 hours before bed",
    "A short wind-down routine signals your body it's time to rest",
    "Keep your bedroom for sleep only, not scrolling or work",
)

_ACTIVE_RECOVERY_TIPS = (
    "8000–10000 steps daily — even on rest days",
    "Foam roll after training sessions",
    "Light walk or mobility on rest days",
    "If soreness is extreme, skip the day",
    "Gentle stretching before bed can ease next-day stiffness",
    "A short walk after meals helps digestion and blood sugar",
    "Alternate hard and easy training days, don't stack two max-effort days back to back",
    "Hydrate through the day, not all at once before training",
)

_STRESS_RECOVERY_TIPS = (
    "5-10 minutes of quiet breathing can lower training-day stress",
    "Chronic high stress blunts recovery as much as poor sleep does",
    "A short outdoor break midday helps reset focus and mood",
    "Notice if soreness lingers past 72h — that's a signal to back off, not push through",
)

_TIP_CATEGORIES = (
    ("Sleep protocol", _SLEEP_TIPS),
    ("Active recovery", _ACTIVE_RECOVERY_TIPS),
    ("Managing stress", _STRESS_RECOVERY_TIPS),
)

_RECOVERY_GOAL_KEYWORDS = ("recovery", "recover", "deload", "injury", "rehab")


def _is_recovery_goal(goal_raw: str) -> bool:
    goal_lower = str(goal_raw or "").lower()
    return any(k in goal_lower for k in _RECOVERY_GOAL_KEYWORDS)


def build_recovery_section(profile: dict, cycle_number: int | None = None) -> dict:
    """Returns the same shape _RECOVERY_DEFAULT does (daily_nonneg,
    key_numbers, tip_sections) — drop-in for what Gemini used to generate
    for the `recovery` key of the plan schema."""
    member_id = profile.get("_member_id", "anonymous")
    cycle = cycle_number if cycle_number is not None else profile.get("_cycle_number", 1)
    goal_raw = profile.get("goal", "")
    recovery_goal = _is_recovery_goal(goal_raw)

    # ── daily_nonneg / key_numbers: goal-aware, not one fixed set ──────────
    if recovery_goal:
        sleep_target, steps_target = "8.5–9.5 h", "6K–8K"
    else:
        sleep_target, steps_target = "7.5–9 h", "10K"

    daily_nonneg = [
        {"icon": "💧", "value": "3.5–4 L", "label": "Water"},
        {"icon": "👟", "value": steps_target, "label": "Steps"},
        {"icon": "🌙", "value": sleep_target, "label": "Sleep"},
        {"icon": "☀️", "value": "A.M.", "label": "Sunlight"},
    ]
    key_numbers = [
        {"icon": "💧", "value": "3.5–4 L", "label": "Water daily"},
        {"icon": "👟", "value": steps_target.replace("K", ",000"), "label": "Steps daily"},
        {"icon": "🌙", "value": sleep_target, "label": "Sleep target"},
        {"icon": "⏰", "value": "2 PM", "label": "Last caffeine"},
    ]

    # ── tip_sections: 2 categories shown per generation, deterministically
    # rotated by (member_id, cycle) so repeat cycles aren't byte-identical.
    # A recovery-flagged goal always includes "Managing stress" (most
    # relevant to that goal) rather than leaving it to chance.
    if recovery_goal:
        chosen_categories = [_TIP_CATEGORIES[0], _TIP_CATEGORIES[2]]  # Sleep + Stress
    else:
        cat_idx = _stable_pick((member_id, cycle, "cat"), len(_TIP_CATEGORIES), 2)
        chosen_categories = [_TIP_CATEGORIES[i] for i in sorted(set(cat_idx)) or [0, 1]]
        if len(chosen_categories) < 2:
            chosen_categories = [_TIP_CATEGORIES[0], _TIP_CATEGORIES[1]]

    tip_sections = []
    for title, pool in chosen_categories:
        idxs = _stable_pick((member_id, cycle, title), len(pool), 4)
        tips = [pool[i] for i in idxs]
        tip_sections.append({"title": title, "tips": tips})

    return {
        "daily_nonneg": daily_nonneg,
        "key_numbers": key_numbers,
        "tip_sections": tip_sections,
    }
